version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    volumes:
      - ./alwayson:/opt/code-scribes/alwayson
